openapi: 3.0.0
info:
  title: {{ cookiecutter.project_slug }}
  description: Monolith that handles all of cortex
  version: 1.0.0
  contact:
    email: founders@getcortexapp.com
  x-cortex-apm:
    datadog:
      slos:
      - 750c16f70eb55bf19f4edd185b8122b3
  x-cortex-git:
    github:
      repository: cortexapps/brain-backend
  x-cortex-tag: {{ cookiecutter.project_slug }}
